aws:
  source_bucket: source-bucket-name
  destination_bucket: destination-bucket-name
  region: us-east-1  # Optional

zip_config:
  source_prefixes:
    - "data/folder1/"
    - "data/folder2/subfolder/"
  output_zip_name: output.zip
  destination_prefix: "processed/data/"  # Optional, defaults to root of bucket
  local_directory: "./output"  # Local directory to store zip files

options:
  compression_level: 9
  delete_local_after: true
  overwrite_s3: false  # Set to true to overwrite existing files in S3

logging:
  level: INFO
  format: "%(asctime)s - %(levelname)s - %(message)s"
  file: logs/s3_zipper.log  # Optional
